### PR TITLE
IT-1874: Remove routes to admincentral

### PR DESCRIPTION
**Pull request by xschildw**
This PR removes the routes to the old VPN on admincentral (10.1.0.0./16). Another PR will remove the peering itself on the other side.

### CODE REVIEW

**Comment by thomasyu888** [comment]
thanks @xschildw! Is this going to impact how I ssh into my instances?

**Comment by xschildw** [comment]
@thomasyu888 , you should not be able to ssh into your issues now. Their security group allows access from 10.1.0.0/16 (the old VPN). We need to change that to 10.50.0.0/16 (TGW).

**Comment by xschildw** [comment]
Security group change will be in nlpsandboxvpc config.

**Comment by xschildw** [comment]
Actually there's some pre-work to associate this VPC with the TGW. Should be tracked in IT-1909.

**Comment by thomasyu888** [comment]
Ahh, right. Thanks @xschildw!  I'm happy to validate and merge this - although is there anything I need to do in the console?

**Review by thomasyu888 — APPROVED** [review]

**Review by zaro0508 — APPROVED** [review]

**Comment by xschildw** [comment]
Forgot I had this one

**Comment by xschildw** [comment]
This is the same as #42, forgot I had it in already...

**Pull request closed without merging**
